#!/bin/sh
#
# install.sh - Installation script for init-selector.
# Run as root.
# POSIX sh compliant.
#
# What it does:
# 1. Detects installed init systems (using detect.sh)
# 2. Creates /etc/init-selector/ directory and config file
# 3. Installs the PID1 init script to /usr/lib/init-selector/init
# 4. Detects initramfs generator (dracut / mkinitcpio / update-initramfs)
# 5. Installs the appropriate integration/hooks/modules
# 6. Rebuilds the initramfs images
#
# After install, reboot and you will get the selector menu (unless kernel param used).
#

set -e

# --- Variables ---
PROJECT_DIR=$(cd "$(dirname "$0")" && pwd)
PREFIX="/usr"
LIBDIR="${PREFIX}/lib/init-selector"
ETCDIR="/etc/init-selector"
CONFIG_FILE="${ETCDIR}/config"
INIT_SCRIPT_SRC="${PROJECT_DIR}/init"
INIT_SCRIPT_DST="${LIBDIR}/init"
DETECT_SCRIPT="${PROJECT_DIR}/detect.sh"

SUPPORTED_INITS="systemd openrc runit dinit sysvinit s6 shepherd finit sinit epoch busybox-init"

# Colors for output (optional, but nice; fall back gracefully)
if [ -t 1 ]; then
    GREEN='\033[0;32m'
    YELLOW='\033[1;33m'
    RED='\033[0;31m'
    NC='\033[0m'
else
    GREEN=''
    YELLOW=''
    RED=''
    NC=''
fi

log() {
    printf "%b\n" "${GREEN}[init-selector]${NC} $*"
}

warn() {
    printf "%b\n" "${YELLOW}[init-selector]${NC} $*"
}

error() {
    printf "%b\n" "${RED}[init-selector]${NC} $*" >&2
}

die() {
    error "$@"
    exit 1
}

# Check root
if [ "$(id -u)" -ne 0 ]; then
    die "This script must be run as root (use sudo or su)"
fi

# --- 1. Detect installed init systems ---
log "Detecting installed init systems..."

if [ ! -f "$DETECT_SCRIPT" ]; then
    die "detect.sh not found in $PROJECT_DIR"
fi

# Capture output of detect.sh
DETECTED=$(sh "$DETECT_SCRIPT" 2>/dev/null || true)

if [ -z "$DETECTED" ]; then
    warn "No init systems detected automatically."
    warn "You will need to manually edit $CONFIG_FILE after installation."
    DETECTED=""
else
    log "Detected: $DETECTED"
fi

# --- 2. Create directories and install files ---
log "Creating directories..."
mkdir -p "$ETCDIR"
mkdir -p "$LIBDIR"

# Copy the main init script
if [ ! -f "$INIT_SCRIPT_SRC" ]; then
    die "init script source not found: $INIT_SCRIPT_SRC"
fi

cp "$INIT_SCRIPT_SRC" "$INIT_SCRIPT_DST"
chmod 755 "$INIT_SCRIPT_DST"

log "Installed init script to $INIT_SCRIPT_DST"

# --- 3. Generate configuration file ---
log "Generating configuration..."

# Write header
cat > "$CONFIG_FILE" << 'EOF'
# init-selector configuration
# Generated by install.sh on $(date)
#
# Format:
#   DEFAULT=<name>
#   <name> <full-path-on-root>
#
# Supported names: systemd, openrc, runit, dinit, sysvinit, s6, shepherd, finit, sinit, epoch, busybox-init
#
# The last chosen init is saved in last file and overrides DEFAULT.
#

EOF

# Add DEFAULT (prefer systemd if present, otherwise first detected)
DEFAULT_NAME="systemd"

# Parse detected list and write entries
# DETECTED is space separated "name:/path name2:/path2"
first_name=""
for pair in $DETECTED; do
    name=${pair%%:*}
    path=${pair#*:}
    # Skip if not supported
    case " $SUPPORTED_INITS " in
        *" $name "*) ;;
        *) continue ;;
    esac

    if [ -z "$first_name" ]; then
        first_name="$name"
    fi

    # Write entry
    printf "%s %s\n" "$name" "$path" >> "$CONFIG_FILE"

    # Choose default: systemd preferred, else first found
    if [ "$name" = "systemd" ]; then
        DEFAULT_NAME="systemd"
    elif [ "$DEFAULT_NAME" = "systemd" ] && [ "$name" != "systemd" ]; then
        # keep systemd if we had it
        :
    fi
done

# If no systemd but others, set first as default
if [ "$DEFAULT_NAME" = "systemd" ] && [ -z "$(grep '^systemd ' "$CONFIG_FILE" 2>/dev/null)" ]; then
    if [ -n "$first_name" ]; then
        DEFAULT_NAME="$first_name"
    fi
fi

# Write DEFAULT at top (we rewrite the file properly)
{
    echo "# init-selector configuration"
    echo "# Generated: $(date)"
    echo "#"
    echo "DEFAULT=$DEFAULT_NAME"
    echo ""
    # Re-add the entries (they were already appended)
} > "${CONFIG_FILE}.tmp"

# Append existing entries (skip previous header)
grep -v '^#' "$CONFIG_FILE" | grep -v '^$' >> "${CONFIG_FILE}.tmp" || true

mv "${CONFIG_FILE}.tmp" "$CONFIG_FILE"
chmod 644 "$CONFIG_FILE"

log "Configuration written to $CONFIG_FILE"
log "Default init: $DEFAULT_NAME"

# Create empty last file (will be populated on first successful boot)
touch "${ETCDIR}/last"
chmod 644 "${ETCDIR}/last"

# --- 4. Detect initramfs generator and install integration ---
log "Detecting initramfs generator..."

DETECTED_GENERATOR=""

# Order of preference: dracut, mkinitcpio, update-initramfs (initramfs-tools)
if command -v dracut >/dev/null 2>&1 && [ -d /usr/lib/dracut ]; then
    DETECTED_GENERATOR="dracut"
elif command -v mkinitcpio >/dev/null 2>&1; then
    DETECTED_GENERATOR="mkinitcpio"
elif command -v update-initramfs >/dev/null 2>&1; then
    DETECTED_GENERATOR="update-initramfs"
else
    warn "No supported initramfs generator found (dracut/mkinitcpio/update-initramfs)."
    warn "You will need to manually integrate the init script into your initramfs."
    warn "See README.md for instructions."
fi

log "Detected generator: ${DETECTED_GENERATOR:-none}"

# --- Install integration functions ---

install_dracut_module() {
    log "Installing dracut module..."

    MODULE_DIR="/usr/lib/dracut/modules.d/99init-selector"
    mkdir -p "$MODULE_DIR"

    # module-setup.sh
    cat > "${MODULE_DIR}/module-setup.sh" << 'DRACUTSETUP'
#!/bin/sh
# dracut module-setup.sh for init-selector

check() {
    # Always include if the module is present
    return 0
}

depends() {
    # No special dependencies
    return 0
}

install() {
    # Install our custom init as the init script (overrides default)
    inst_simple /usr/lib/init-selector/init /init

    # Also copy the config and last file so they are available in initramfs
    # (we will read from real root anyway, but having them early is safe)
    inst_dir /etc/init-selector
    inst_simple /etc/init-selector/config /etc/init-selector/config
    [ -f /etc/init-selector/last ] && inst_simple /etc/init-selector/last /etc/init-selector/last

    # Ensure switch_root is available (dracut usually includes it)
    inst_binary switch_root || true

    # Mark as critical so dracut includes it
    inst_hook cmdline 99 "$moddir/init-selector.sh" || true
}

DRACUTSETUP

    chmod 755 "${MODULE_DIR}/module-setup.sh"

    # Optional hook script (can be empty or add debug)
    cat > "${MODULE_DIR}/init-selector.sh" << 'DRACUTHOOK'
#!/bin/sh
# init-selector dracut hook (cmdline stage)
# Nothing special needed; the /init override does the work.
DRACUTHOOK
    chmod 755 "${MODULE_DIR}/init-selector.sh"

    log "dracut module installed to $MODULE_DIR"
}

install_mkinitcpio_hook() {
    log "Installing mkinitcpio hook..."

    HOOKS_DIR="/etc/initcpio/hooks"
    INSTALL_DIR="/etc/initcpio/install"

    mkdir -p "$HOOKS_DIR" "$INSTALL_DIR"

    # install hook (runs at build time)
    cat > "${INSTALL_DIR}/init-selector" << 'MKINSTALL'
#!/bin/sh

build() {
    # Add our init script as /init inside initramfs
    add_file /usr/lib/init-selector/init /init
    add_dir /etc/init-selector

    # Copy config
    add_file /etc/init-selector/config /etc/init-selector/config

    if [ -f /etc/init-selector/last ]; then
        add_file /etc/init-selector/last /etc/init-selector/last
    fi

    # Ensure switch_root binary is present
    add_binary switch_root
}

help() {
    echo "This hook installs init-selector as PID 1 in the initramfs."
}
MKINSTALL
    chmod 755 "${INSTALL_DIR}/init-selector"

    # runtime hook (runs inside initramfs before /init is executed)
    # We do not need much because our /init is the selector.
    cat > "${HOOKS_DIR}/init-selector" << 'MKHOOK'
#!/bin/sh

run_hook() {
    # The custom /init is already in place.
    # We could add early messages here if wanted.
    echo "init-selector: mkinitcpio hook executed"
}
MKHOOK
    chmod 755 "${HOOKS_DIR}/init-selector"

    log "mkinitcpio hooks installed."

    # Advice to user
    warn "IMPORTANT: Add 'init-selector' to the HOOKS array in /etc/mkinitcpio.conf"
    warn "Example: HOOKS=(base udev autodetect modconf block filesystems fsck init-selector)"
    warn "Then run mkinitcpio -P manually if automatic rebuild fails."
}

install_initramfs_tools() {
    log "Installing for update-initramfs (initramfs-tools)..."

    SCRIPTS_DIR="/usr/share/initramfs-tools/scripts"
    HOOKS_DIR="/usr/share/initramfs-tools/hooks"

    mkdir -p "$SCRIPTS_DIR/initramfs-tools" "$HOOKS_DIR"

    # We use a bottom script that overrides /init at the end
    # initramfs-tools runs scripts in order: init, local, etc.
    # Best: use a hook to copy our script over /init

    cat > "${HOOKS_DIR}/init-selector" << 'IFHOOK'
#!/bin/sh
# initramfs-tools hook for init-selector

PREREQ=""
prereqs() { echo "$PREREQ"; }

case "$1" in
    prereqs)
        prereqs
        exit 0
        ;;
esac

. /usr/share/initramfs-tools/hook-functions

# Copy the selector init
if [ -f /usr/lib/init-selector/init ]; then
    copy_exec /usr/lib/init-selector/init /init
fi

# Copy config
if [ -d /etc/init-selector ]; then
    mkdir -p ${DESTDIR}/etc/init-selector
    cp -a /etc/init-selector/* ${DESTDIR}/etc/init-selector/ 2>/dev/null || true
fi

# Ensure switch_root
copy_exec /bin/switch_root || copy_exec /sbin/switch_root || true
IFHOOK
    chmod 755 "${HOOKS_DIR}/init-selector"

    log "initramfs-tools hook installed to $HOOKS_DIR/init-selector"

    # We can also add a script in scripts/ if needed, but hook is sufficient
    warn "update-initramfs will automatically pick up the hook."
}

# --- Call the correct installer ---
case "$DETECTED_GENERATOR" in
    dracut)
        install_dracut_module
        ;;
    mkinitcpio)
        install_mkinitcpio_hook
        ;;
    update-initramfs)
        install_initramfs_tools
        ;;
    *)
        warn "Skipping automatic integration."
        ;;
esac

# --- 5. Rebuild initramfs ---
log "Rebuilding initramfs..."

rebuild_success=0

case "$DETECTED_GENERATOR" in
    dracut)
        # Rebuild all current kernels
        if command -v dracut >/dev/null; then
            # Find kernels
            for kverdir in /usr/lib/modules/*; do
                [ -d "$kverdir" ] || continue
                kver=${kverdir##*/}
                if [ -f "${kverdir}/vmlinuz" ] || [ -f "/boot/vmlinuz-${kver}" ]; then
                    log "Rebuilding dracut for kernel $kver"
                    if dracut --force --no-hostonly-cmdline "/boot/initramfs-${kver}.img" "$kver" 2>&1; then
                        log "  Success: /boot/initramfs-${kver}.img"
                        rebuild_success=1
                    else
                        warn "  Failed to rebuild for $kver (you may need to run manually)"
                    fi
                fi
            done

            # Fallback if no kernels found above: try generic rebuild
            if [ "$rebuild_success" = "0" ]; then
                dracut --force --no-hostonly-cmdline 2>&1 || warn "dracut generic rebuild failed"
            fi
        fi
        ;;

    mkinitcpio)
        if command -v mkinitcpio >/dev/null; then
            log "Running mkinitcpio -P (all presets)"
            if mkinitcpio -P 2>&1; then
                rebuild_success=1
                log "mkinitcpio rebuild completed"
            else
                warn "mkinitcpio -P failed. Please run manually after editing /etc/mkinitcpio.conf"
            fi
        fi
        ;;

    update-initramfs)
        if command -v update-initramfs >/dev/null; then
            log "Running update-initramfs -u -k all"
            if update-initramfs -u -k all 2>&1; then
                rebuild_success=1
                log "update-initramfs completed"
            else
                warn "update-initramfs failed. Try 'update-initramfs -u -k all' manually"
            fi
        fi
        ;;

    *)
        warn "No automatic rebuild performed."
        warn "Please rebuild your initramfs manually using your distribution's tool."
        ;;
esac

# --- Final instructions ---
echo ""
log "Installation complete!"
echo ""
echo "Next steps:"
echo "  1. Review configuration: cat $CONFIG_FILE"
echo "  2. (Optional) Edit $CONFIG_FILE to adjust DEFAULT or paths"
echo "  3. Reboot the system"
echo "  4. At boot you should see the init-selector menu (unless initsel= param used)"
echo ""
echo "Kernel parameters supported:"
echo "  initsel=systemd   initsel=openrc   initsel=runit   initsel=dinit"
echo "  initsel=sysvinit  initsel=s6       initsel=shepherd"
echo "  initsel=finit     initsel=sinit    initsel=epoch"
echo "  initsel=busybox-init"
echo ""
echo "To remove later, see README.md or run the uninstall steps."
echo ""

if [ "$rebuild_success" = "1" ]; then
    log "Initramfs rebuild succeeded."
else
    warn "Initramfs rebuild may have had issues. Check logs above and rebuild manually."
fi

exit 0
